import { useCallback, useEffect, useState } from "react";
import api from "../api/axios";
import { Icon } from "../components/Navbar.jsx";

export default function Students() {
  const [students, setStudents] = useState([]); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const limit = 20;
  const load = useCallback(() => { setLoading(true); setError(""); api.get("/students", { params: { search: query, page, limit } }).then(({data}) => { setStudents(data.students); setTotal(data.total); }).catch((err) => setError(err.response?.data?.message || "Unable to load student registrations.")).finally(() => setLoading(false)); }, [query, page]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  const exportStudents = async () => { const response = await api.get("/students/export", { params: { search: query }, responseType: "blob" }); const url = URL.createObjectURL(response.data); const a = document.createElement("a"); a.href = url; a.download = "examplat-student-status.xlsx"; a.click(); URL.revokeObjectURL(url); };
  const pages = Math.max(1, Math.ceil(total / limit));
  return <div className="mx-auto max-w-7xl space-y-7"><section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="page-kicker">Registration desk</p><h1 className="page-title">Students</h1><p className="page-subtitle">View registered students, payment status, and examination bookings.</p></div><button onClick={exportStudents} className="btn-secondary gap-2"><span className="text-base">⇩</span>Download XLSX</button></section>
    <div className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><div className="relative max-w-xl"><span className="absolute left-3 top-2.5 text-slate-400">⌕</span><input className="input pl-8" value={query} onChange={(e) => {setQuery(e.target.value);setPage(1);}} placeholder="Search name, email, mobile, or hall ticket number…" /></div></div><div className="flex justify-between px-5 py-3 text-xs text-slate-500"><span>{loading ? "Loading…" : `${total} registered students`}</span><span>Payment and booking data are from the registration portal</span></div>
      <div className="table-wrap"><table className="min-w-[980px] w-full text-sm"><thead className="border-y border-slate-100 bg-slate-50/80 text-left text-[11px] font-bold uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Hall ticket</th><th className="px-5 py-3">Booked exams</th><th className="px-5 py-3">Payment</th><th className="px-5 py-3">Registered</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-400">Loading registrations…</td></tr> : error ? <tr><td colSpan={6} className="px-5 py-12 text-center text-red-600">{error}</td></tr> : students.length === 0 ? <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-400">No students match this search.</td></tr> : students.map((student) => <tr key={student.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{student.name}</p><p className="mt-1 text-xs text-slate-400">{student.email || "No email"}</p></td><td className="px-5 py-4 text-slate-600">{student.mobile || "—"}</td><td className="px-5 py-4 font-mono text-xs text-slate-600">{student.hallTicketNo || "—"}</td><td className="px-5 py-4 text-slate-600">{student.exams.length ? student.exams.join(", ") : "—"}</td><td className="px-5 py-4"><span className={`badge ${student.paymentStatus.toLowerCase() === "paid" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{student.paymentStatus}</span></td><td className="px-5 py-4 text-xs text-slate-500">{student.registeredAt ? new Date(student.registeredAt).toLocaleDateString() : "—"}</td></tr>)}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-sm text-slate-500"><span>Page {page} of {pages}</span><div className="flex gap-2"><button disabled={page === 1} className="btn-secondary py-1.5 text-xs" onClick={() => setPage((p) => p - 1)}>Previous</button><button disabled={page === pages} className="btn-secondary py-1.5 text-xs" onClick={() => setPage((p) => p + 1)}>Next</button></div></div>
    </div></div>;
}
